(make-string 5 #\a)
(make-string 0 #\c)
(string-upcase "aCcD01-E")
(string-downcase "aCcD01-E")
(string-foldcase "aCcD01-E")
(substring "hello world" 3 7)
(string->list "hello world")
(list->string (list #\h #\e #\l #\l #\o #\space #\w #\o #\r #\l #\d))